### ISSUE TITLE
any big sur update?

### ISSUE THREAD

**Issue by johanpedroo** [MrGeque/Dell-Inspiron-7573-OpenCore-Hackintosh#2]
Have success with big sur?

**Comment by MrGeque** [comment]
yes Big Sur works with my configuration. However the 4k panel (if you use one) will only be limited to 48hz refresh rate. ill update the files to reflect the changes. my setup currently runs Big Sur but only with an external monitor. if you look at my guide on tonymac site, post #23 has prebuilt config.plist with the changes. I won't add another config.plist to repo until I have the screen working without an edid patch
