### ISSUE TITLE
BCM94360CS Install guide

### ISSUE THREAD

**Issue by sebasinparis** [MrGeque/Dell-Inspiron-7573-OpenCore-Hackintosh#3]
Here
[SSD Install.zip](https://github.com/MrGeque/Dell-Inspiron-7573-OpenCore-Hackintosh/files/5585610/SSD.Install.zip)
[WIFI Install.zip](https://github.com/MrGeque/Dell-Inspiron-7573-OpenCore-Hackintosh/files/5585611/WIFI.Install.zip)
[Potential Final Look.zip](https://github.com/MrGeque/Dell-Inspiron-7573-OpenCore-Hackintosh/files/5585612/Potential.Final.Look.zip)

**Comment by MrGeque** [comment]
agreed. send me direct email

**Comment by sebasinparis** [comment]
I couldn't find your email in your profile so I'll leave mine. Please delete this issue right after

[Untitled.rtf.zip](https://github.com/MrGeque/Dell-Inspiron-7573-OpenCore-Hackintosh/files/5592029/Untitled.rtf.zip)

**Comment by MrGeque** [comment]
gonna send email to you in daytime.
